"""add delete to comment model

Revision ID: fc14a414d00e
Revises: 33889bd1495a
Create Date: 2020-09-30 03:36:36.600703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc14a414d00e'
down_revision = '33889bd1495a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'deleted')
    # ### end Alembic commands ###
